apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worldhealth
  labels:
    app: worldhealth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worldhealth
  template:
    metadata:
      labels:
        app: worldhealth
    spec:
      containers:
      - name: worldhealth
        image: ghost:2.26-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://my-blog.com
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
