apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worldhealth
  labels:
    app: worldhealth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worldhealth
  template:
    metadata:
      labels:
        app: worldhealth
    spec:
      containers:
      - name: ghost
        image: ghost:2.25-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://my-blog.com
